version: '3.8'

services:
  fastapi-llm:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LLM_MODEL=gemini-pro
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - llm-network

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   networks:
  #     - llm-network

  # Optional: Add PostgreSQL for data persistence
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: llm_service
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - llm-network

networks:
  llm-network:
    driver: bridge

# volumes:
#   postgres_data:
