[project]
name = "manimato-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.11.0",
    "fastapi>=0.115.14,<1.0.0",
    "langchain==0.1.20",
    "langchain-community>=0.0.38,<1.0.0",
    "langchain-openai==0.1.7",
    "uvicorn[standard]>=0.35.0,<1.0.0",
]


[dependency-groups]
dev = [
  "taskipy>=1.14.1",
  "black>=25.1.0",
  "ruff>=0.12.2",
  "pytest",
  "taskipy"
]

[tool.taskipy.tasks]
dev = "uvicorn app.main:app --reload"
start = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
format = "black ."
lint = "ruff check ."
lint-fix = "ruff check . --fix"
test = "pytest"
export = "uv export --format=requirements.txt --without-hashes > requirements.txt"

