"""add content field in code

Revision ID: 46a5481cba34
Revises: 8de7a019407a
Create Date: 2025-07-13 20:59:34.939884

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46a5481cba34"
down_revision: Union[str, Sequence[str], None] = "8de7a019407a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("codes", sa.Column("code", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("codes", "code")
    # ### end Alembic commands ###
